### ISSUE TITLE
Menu msg parameter - wrapping the string or adding \n does not work as expected.

### ISSUE THREAD

**Issue by Normanras** [domdfcoding/whiptail#41]
## Description
For the message parameter in the menu function using "some string \n some strong" does not actually show the new line portion of the string. At the same time, for strings that are very very long, the string runs off the side of the dialog box. 

I tested this in all other options/functions and both newline and wrap works as expected. 

## Steps to Reproduce
Add `\n` to the `msg` in menu function or create a very very long string for the menu `msg`. 

If possible, please include a small, self-contained reproduction.
-->
Single step, see above. 

## Actual result:
Here are some examples:
![Menu 1 No wrap](https://user-images.githubusercontent.com/44226464/187462699-a98a7bcc-3a9e-4b49-bc71-6fa7831c9d4b.png)
![Radiolist Working Wrap](https://user-images.githubusercontent.com/44226464/187462703-7515ca6a-7b00-4591-9bf3-ed6d0ffe7b09.png)
![Radiolist Working New Line](https://user-images.githubusercontent.com/44226464/187462705-0d2b2ac1-fbf1-4b32-a941-8210600bc3f5.png)
![Menu No New Line](https://user-images.githubusercontent.com/44226464/187462707-1e38136a-403c-4343-b1fa-35f54b19c94a.png)

## Expected result:
New line or wrap of string in box

## Reproduces how often:
Easily Reproduced

## Version

  * Operating System: Mac 12.5.1
  * Python: 3.10.6
  * whiptail: newt 0.52.21

## Installation source
VirtualEnv > Pip

## Other Additional Information:
I've found the issue, fixed it locally, and will submit a PR soon. I updated all of the `msg` parameters in `test.py`, so please let me know if you'd like me to not include those extra long strings and I can resubmit.

**Comment by domdfcoding** [comment]
Fixed by #42
